### ISSUE TITLE
Historical mistake

### ISSUE THREAD

**Issue by pofigizm** [beerjs/moscow#2]
Meetups were held at the PivBar several times. Everything was ok.

One of them (06.08.2015) is .... ( then https://github.com/beerjs/moscow/commit/f219dedcee29ff954640e9da869fed2a44607d86 )

@mishk0 @lolmaus

**Comment by pofigizm** [comment]
![img_20150618_223626](https://cloud.githubusercontent.com/assets/6995947/9154450/4655b25e-3e97-11e5-8f8f-eee8e5ebd637.jpg)

**Comment by lolmaus** [comment]
Do you imply that we should stay with PivBar?

**Comment by mishk0** [comment]
Anyway, if we expect more then 6 people, PivBar will be inconvenient. Very crowded and no reservation

**Comment by lolmaus** [comment]
I know of a decent place. It has craft beer, hot food, non-alcoholic drinks. I'm not sure about table reservations, but there always are free tables.

It's only drawback is that it's not close to metro. It's located next to the Baumanskaya station which is closed for maintenance. It's a 25-minute walk from Krasnoselskaya (red line), or a trollebus ride from Komsomolskaya (red) or Elektrozavodskaya (blue).

**Comment by pofigizm** [comment]
@lolmaus , I mean that your commit looks like the Meetup was only one and no more.

**Comment by lolmaus** [comment]
Who's going tomorrow (2014.08.13)? We should decide on the place.
