### ISSUE TITLE
Gitter chat

### ISSUE THREAD

**Issue by chicoxyzzy** [beerjs/moscow#4]
Could you please create room in Gitter to move our flood away from [MoscowJS chat](https://gitter.im/MoscowJS/chat)?

**Comment by chicoxyzzy** [comment]
Also add admin roles in that room to @lolmaus, @vmakhaev and @chicoxyzzy please

**Comment by mishk0** [comment]
done https://gitter.im/beerjs/moscow

**Comment by chicoxyzzy** [comment]
thank you!
