### ISSUE TITLE
Plan to visit all point on this map! Repeats are not allowed!

### ISSUE THREAD

**Issue by pofigizm** [beerjs/moscow#8]
http://russiancraftbeer.ru

**Comment by chicoxyzzy** [comment]
у нас баг в баге(

**Comment by vslinko** [comment]
это ты про эрика?

**Comment by chicoxyzzy** [comment]
я про то, что вот эта ишью не работает(

**Comment by chicoxyzzy** [comment]
а ты про что?

**Comment by vslinko** [comment]
я про то, что мы в эрик ходим постоянно и не придерживаемся "Repeats are not allowed"

**Comment by pofigizm** [comment]
Все! Вводим запрет на Эрик!
